//category: {aero, lightweight, tt, gravel, cyclocross, endurance}
export const BikeBrandsModels = [
    {make: "Giant", model: "TCR", category: "lightweight", color: "#000000"},
    {make: "Giant", model: "Defy", category: "endurance", color: "#000000"},
    {make: "Giant", model: "Propel", category: "aero", color: "#000000"},
    {make: "Giant", model: "Trinity", category: "tt", color: "#000000"},
    {make: "Giant", model: "TCX", category: "gravel", color: "#000000"},
    {make: "Giant", model: "Revolt", category: "gravel", color: "#000000"},
    {make: "Liv", model: "Langma", category: "lightweight", color: "#000000"},
    {make: "Liv", model: "Avail", category: "endurance", color: "#000000"},
    {make: "Liv", model: "Devote", category: "lightweight", color: "#000000"},
    {make: "Liv", model: "Brava", category: "cyclocross", color: "#000000"},
    {make: "Orbea", model: "Orca", category: "lightweight", color: "#000000"},
    {make: "Orbea", model: "Orca Aero", category: "aero", color: "#000000"},
    {make: "Orbea", model: "Avant", category: "endurance", color: "#000000"},
    {make: "Orbea", model: "Terra", category: "gravel", color: "#000000"},
    {make: "Orbea", model: "Ordu", category: "aero", color: "#000000"},
    {make: "Specialized", model: "Aethos", category: "lightweight", color: "#000000"},
    {make: "Specialized", model: "Tarmac SL6", category: "lightweight", color: "#000000"},
    {make: "Specialized", model: "Tarmac SL7", category: "aero", color: "#000000"},
    {make: "Specialized", model: "Roubaix", category: "endurance", color: "#000000"},
    {make: "Specialized", model: "Shiv TT", category: "tt", color: "#000000"},
    {make: "Look", model: "795 Blade", category: "aero", color: "#000000"},
    {make: "Look", model: "785 Huez", category: "lightweight", color: "#000000"},
    {make: "Look", model: "765 Optimum", category: "endurance", color: "#000000"},
    {make: "Time", model: "ALPE D'HUEZ", category: "lightweight", color: "#000000"},
    {make: "Time", model: "SCYLON", category: "aero", color: "#000000"},
    {make: "Cervelo", model: "S5", category: "aero", color: "#000000"},
    {make: "Cervelo", model: "R5", category: "lightweight", color: "#000000"},
    {make: "Cervelo", model: "Soloist", category: "aero", color: "#000000"},
    {make: "Cervelo", model: "Caledonia-5", category: "endurance", color: "#000000"},
    {make: "Cervelo", model: "Caledonia", category: "endurance", color: "#000000"},
    {make: "Cervelo", model: "P5", category: "tt", color: "#000000"},
    {make: "Cervelo", model: "Aspero-5", category: "gravel", color: "#000000"},
    {make: "Cervelo", model: "Aspero", category: "gravel", color: "#000000"},
    {make: "Cervelo", model: "R5-CX", category: "cyclocross", color: "#000000"},
    {make: "Canyon", model: "Aeroad", category: "aero", color: "#000000"},
    {make: "Canyon", model: "Speedmax", category: "aero", color: "#000000"},
    {make: "Canyon", model: "Ultimate", category: "lightweight", color: "#000000"},
    {make: "Canyon", model: "Endurace", category: "aero", color: "#000000"},
    {make: "Canyon", model: "Inflite", category: "cyclocross", color: "#000000"},
    {make: "Trek", model: "Madone", category: "aero", color: "#000000"},
    {make: "Trek", model: "Emonda", category: "lightweight", color: "#000000"},
    {make: "Trek", model: "Domane", category: "endurance", color: "#000000"},
    {make: "Trek", model: "Checkpoint", category: "gravel", color: "#000000"},
    {make: "Trek", model: "Domane", category: "gravel", color: "#000000"},
    {make: "Cannondale", model: "SuperSix", category: "gravel", color: "#000000"},
    {make: "Cannondale", model: "CAAD13", category: "gravel", color: "#000000"},
    {make: "Cannondale", model: "Optimo", category: "gravel", color: "#000000"},
    {make: "Scott", model: "Addict RC", category: "lightweight", color: "#000000"},
    {make: "Scott", model: "Addict", category: "endurance", color: "#000000"},
    {make: "Scott", model: "Speedster", category: "endurance", color: "#000000"},
    {make: "Scott", model: "Metrix", category: "endurance", color: "#000000"},
    {make: "Scott", model: "Foil RC", category: "aero", color: "#000000"},
    {make: "Scott", model: "Plasma", category: "aero", color: "#000000"},
    {make: "Scott", model: "Contessa Addict SE", category: "lightweight", color: "#000000"},
    {make: "Scott", model: "Contessa Addict", category: "aero", color: "#000000"},
    {make: "Scott", model: "Contessa Speedster", category: "aero", color: "#000000"},
    {make: "Scott", model: "Contessa Addict Gravel", category: "aero", color: "#000000"},
    {make: "Scott", model: "Contessa Speedster Gravel", category: "aero", color: "#000000"},
    {make: "Ridley", model: "Noah", category: "aero", color: "#000000"},
    {make: "Ridley", model: "Fenix", category: "endurance", color: "#000000"},
    {make: "Ridley", model: "Helium", category: "lightweight", color: "#000000"},
    {make: "Ridley", model: "Kanzo", category: "gravel", color: "#000000"},

];